baseURL                       = "https://islandofwords.xyz"
languageCode                  = "id"
title                         = "Island of Words"
theme                         = "personal-site"
summaryLength                 = 10
homepage = "https://islandofwords.xyz"

[Author] # Used in authorbox
  name                        = "Shalu"
  bio                         = ""
  avatar                      = "/images/islandLogo.png"
  job                         = "Content Writer"
  gender                      = "female"
  email                       = "shalakasp66@gmail.com"


[Params]
  subTitle                    = "Shalu's Personal Blog"
  description                 = "Personal blog where I write about the diverse topics like literature and interesting events" # Site Description. Used in meta description
  images                      = ["/images/islandLogo.png"]
  #copyright                   = "Wisnuwiry" # Copyright holder, otherwise will use .Site.Title
  opengraph                   = true # Enable OpenGraph if true
  twitter_cards               = true # Enable Twitter Cards if true
  mainSections                = ["post"] # Set main page sections
  dateFormat                  = "January 02, 2006" # Change the format of dates
  # customCSS                 = ["css/custom.css"] # Include custom CSS files
  customJS                    = []
  mainMenuAlignment           = "right" # Align main menu (desktop version) to the right side
  authorbox                   = true # Show authorbox at bottom of single pages if true
  comments                    = true # Enable comments for all site pages
  related                     = true # Enable Related content for single pages
  relatedMax                  = 5
  mathjax                     = false # Enable MathJax for all site pages
  hideNoPostsWarning          = false # Don't show no posts empty state warning in main page, if true
  fontUnit                    = "em"
  largestFontSize             = 2.5
  smallestFontSize            = 1
  #googleSearchConsole         = ""
  # GoogleAnalytics             = ""
  # fb_admins                   = 
  # fb_app_id                   = 
  paginateLength              = 5
  # adsenseId                   = 

  # Google Search custom, more info: https://cse.google.com/cse/all
 # customSearchId              = "004021659876411083349:a2ysxpichpc"

  #endMessagePost              = "Please leave your comments. Comments are welcome "
  
  # Link repo to edit content
  # editContentPageLink         = "https://github.com/wisnuwiry/blog-v2/edit/master/content/"
  
  # Formspree form contact id, more info: https://cse.google.com/cse/all
  # formspreeId                 = ""
  

[Params.Hero]
  title                       = "Shalu's Blog"
  desc                        = "Welcome to my Blog. This is where  I review books and write short stories :)"

[Params.Entry]
  meta                        = ["date", "categories"] # Enable meta fields in given order
  toc                         = true # Enable Table of Contents
  tocOpen                     = false # Open Table of Contents block. Optional

[Params.Featured]
  previewOnly                 = false # Show only preview featured image

[Params.Comments]
  repository                  = "" # Repository to host your comment, ex: username/repo

# Navigation bar
[menu]

[[menu.main]]
identifier = "Post"
pre = "📝"
url = "/post" 
weight = 1 

# [[menu.main]]
# identifier = "Snippet"
# pre = "⚒️"
# url = "/snippet" 
# weight = 2 

# [[menu.main]]
# identifier = "Project"
# pre = "🚧"
# url = "/project" 
# weight = 3 

[[menu.main]]
identifier = "About"
pre = "😃"
url = "/about" 
weight = 2

[[menu.main]]
identifier = "Contact"
pre = "🤙"
url = "/contact" 
weight = 3

[Params.Breadcrumb]
  enable                      = true # Enable breadcrumb block globally
  homeText                    = "Home" # Home node text

[Params.Social]
#  twitter                     = "jhon-doe"
#  telegram                    = "jhon-doe"
 instagram                   = "jhon-doe"
#  linkedin                    = "wisnu-saputra"
#  github                      = "jhon-doe"
#  gitlab                      = "jhon-doe"
#  medium                      = "jhon-doe"

[Params.Share] # Entry Share block
  facebook                    = true
  twitter                     = true
  reddit                      = false
  telegram                    = false
  linkedin                    = true
  pinterest                   = true

# Web App Manifest settings
# https://www.w3.org/TR/appmanifest/
# https://developers.google.com/web/fundamentals/web-app-manifest/
[Params.Manifest]
  name                        = "Shalu's Blog"
  shortName                   = "Shalu's Blog"
  display                     = "standalone"
  startUrl                    = "/?utm_source=homescreen"
  backgroundColor             = "#8dc153"
  themeColor                  = "#1da1f2"
  description                 = "Shalu's personal blog"
  orientation                 = "portrait"
  scope                       = "/"

[outputFormats]
  [outputFormats.MANIFEST]
    mediaType                 = "application/json"
    baseName                  = "manifest"
    isPlainText               = true
    notAlternative            = true

[outputs]
  home                        = ["HTML", "RSS", "MANIFEST"]

enableRobotsTXT               = true

# Pagination
Paginate                      = 3
 

# Code
[markup]
  # defaultMarkdownHandler    = "blackfriday"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList          = true
      footnote                = true
      linkify                 = true
      strikethrough           = true
      table                   = true
      taskList                = true
      typographer             = true
    [markup.goldmark.parser]
      attribute               = true
      autoHeadingID           = true
      autoHeadingIDType       = "github"
    [markup.goldmark.renderer]
      hardWraps               = false
      unsafe                  = true
      xhtml                   = false
  [markup.blackFriday]
    angledQuotes              = false
    footnoteAnchorPrefix      = ""
    footnoteReturnLinkContents= ""
    fractions                 = true
    hrefTargetBlank           = false
    latexDashes               = true
    nofollowLinks             = false
    noreferrerLinks           = false
    plainIDAnchors            = true
    skipHTML                  = false
    smartDashes               = true
    smartypants               = true
    smartypantsQuotesNBSP     = false
    taskLists                 = true
  [markup.highlight]
    codeFences                = true
    guessSyntax               = false
    hl_Lines                  = ""
    lineNoStart               = 1
    lineNos                   = false
    lineNumbersInTable        = false
    noClasses                 = false
    style                     = "dracula"
    tabWidth                  = 4
  [markup.tableOfContents]
    endLevel                  = 3
    ordered                   = false
    startLevel                = 2
